openapi: 3.0.3
info:
  title: BridgeBloc API
  version: 1.0.0
  description: BridgeBloc API
paths:
  /api/ping:
    get:
      operationId: ping_retrieve
      tags:
      - ping
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
