# Generated by Django 4.2.4 on 2023-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenconversionstep',
            name='step_type',
            field=models.CharField(
                choices=[
                    ('confirm deposit', 'Confirm Deposit'),
                    ('send to recipient', 'Send To Recipient'),
                    ('create deposit address', 'Create Deposit Address'),
                    ('attestation service confirmation', 'Attestation Service Confirmation'),
                    ('send to recipient', 'Send To Recipient'),
                ],
                max_length=150,
                verbose_name='step type',
            ),
        ),
    ]
